/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as RecruitersRouteImport } from './routes/recruiters'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAppliedRouteImport } from './routes/app.applied'
import { Route as AppBureauRouteImport } from './routes/app.bureau'
import { Route as AppCandidatesRouteImport } from './routes/app.candidates'
import { Route as AppDepartureRouteImport } from './routes/app.departure'
import { Route as AppJobsRouteImport } from './routes/app.jobs'
import { Route as AppMedicalRouteImport } from './routes/app.medical'
import { Route as AppOfferRouteImport } from './routes/app.offer'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSortedRouteImport } from './routes/app.sorted'
import { Route as AppTicketRouteImport } from './routes/app.ticket'
import { Route as AppVisaRouteImport } from './routes/app.visa'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitersRoute = RecruitersRouteImport.update({
  id: '/recruiters',
  path: '/recruiters',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppliedRoute = AppAppliedRouteImport.update({
  id: '/applied',
  path: '/applied',
  getParentRoute: () => AppRoute,
} as any)
const AppBureauRoute = AppBureauRouteImport.update({
  id: '/bureau',
  path: '/bureau',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidatesRoute = AppCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartureRoute = AppDepartureRouteImport.update({
  id: '/departure',
  path: '/departure',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppMedicalRoute = AppMedicalRouteImport.update({
  id: '/medical',
  path: '/medical',
  getParentRoute: () => AppRoute,
} as any)
const AppOfferRoute = AppOfferRouteImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSortedRoute = AppSortedRouteImport.update({
  id: '/sorted',
  path: '/sorted',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketRoute = AppTicketRouteImport.update({
  id: '/ticket',
  path: '/ticket',
  getParentRoute: () => AppRoute,
} as any)
const AppVisaRoute = AppVisaRouteImport.update({
  id: '/visa',
  path: '/visa',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/jobs': typeof JobsRoute
  '/recruiters': typeof RecruitersRoute
  '/app/applied': typeof AppAppliedRoute
  '/app/bureau': typeof AppBureauRoute
  '/app/candidates': typeof AppCandidatesRoute
  '/app/departure': typeof AppDepartureRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/medical': typeof AppMedicalRoute
  '/app/offer': typeof AppOfferRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/sorted': typeof AppSortedRoute
  '/app/ticket': typeof AppTicketRoute
  '/app/visa': typeof AppVisaRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/recruiters': typeof RecruitersRoute
  '/app/applied': typeof AppAppliedRoute
  '/app/bureau': typeof AppBureauRoute
  '/app/candidates': typeof AppCandidatesRoute
  '/app/departure': typeof AppDepartureRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/medical': typeof AppMedicalRoute
  '/app/offer': typeof AppOfferRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/sorted': typeof AppSortedRoute
  '/app/ticket': typeof AppTicketRoute
  '/app/visa': typeof AppVisaRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/jobs': typeof JobsRoute
  '/recruiters': typeof RecruitersRoute
  '/app/applied': typeof AppAppliedRoute
  '/app/bureau': typeof AppBureauRoute
  '/app/candidates': typeof AppCandidatesRoute
  '/app/departure': typeof AppDepartureRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/medical': typeof AppMedicalRoute
  '/app/offer': typeof AppOfferRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/sorted': typeof AppSortedRoute
  '/app/ticket': typeof AppTicketRoute
  '/app/visa': typeof AppVisaRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/jobs'
    | '/recruiters'
    | '/app/applied'
    | '/app/bureau'
    | '/app/candidates'
    | '/app/departure'
    | '/app/jobs'
    | '/app/medical'
    | '/app/offer'
    | '/app/settings'
    | '/app/sorted'
    | '/app/ticket'
    | '/app/visa'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/jobs'
    | '/recruiters'
    | '/app/applied'
    | '/app/bureau'
    | '/app/candidates'
    | '/app/departure'
    | '/app/jobs'
    | '/app/medical'
    | '/app/offer'
    | '/app/settings'
    | '/app/sorted'
    | '/app/ticket'
    | '/app/visa'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/jobs'
    | '/recruiters'
    | '/app/applied'
    | '/app/bureau'
    | '/app/candidates'
    | '/app/departure'
    | '/app/jobs'
    | '/app/medical'
    | '/app/offer'
    | '/app/settings'
    | '/app/sorted'
    | '/app/ticket'
    | '/app/visa'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  JobsRoute: typeof JobsRoute
  RecruitersRoute: typeof RecruitersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiters': {
      id: '/recruiters'
      path: '/recruiters'
      fullPath: '/recruiters'
      preLoaderRoute: typeof RecruitersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/applied': {
      id: '/app/applied'
      path: '/applied'
      fullPath: '/app/applied'
      preLoaderRoute: typeof AppAppliedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bureau': {
      id: '/app/bureau'
      path: '/bureau'
      fullPath: '/app/bureau'
      preLoaderRoute: typeof AppBureauRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/candidates': {
      id: '/app/candidates'
      path: '/candidates'
      fullPath: '/app/candidates'
      preLoaderRoute: typeof AppCandidatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/departure': {
      id: '/app/departure'
      path: '/departure'
      fullPath: '/app/departure'
      preLoaderRoute: typeof AppDepartureRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/jobs': {
      id: '/app/jobs'
      path: '/jobs'
      fullPath: '/app/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/medical': {
      id: '/app/medical'
      path: '/medical'
      fullPath: '/app/medical'
      preLoaderRoute: typeof AppMedicalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/offer': {
      id: '/app/offer'
      path: '/offer'
      fullPath: '/app/offer'
      preLoaderRoute: typeof AppOfferRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sorted': {
      id: '/app/sorted'
      path: '/sorted'
      fullPath: '/app/sorted'
      preLoaderRoute: typeof AppSortedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ticket': {
      id: '/app/ticket'
      path: '/ticket'
      fullPath: '/app/ticket'
      preLoaderRoute: typeof AppTicketRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/visa': {
      id: '/app/visa'
      path: '/visa'
      fullPath: '/app/visa'
      preLoaderRoute: typeof AppVisaRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAppliedRoute: typeof AppAppliedRoute
  AppBureauRoute: typeof AppBureauRoute
  AppCandidatesRoute: typeof AppCandidatesRoute
  AppDepartureRoute: typeof AppDepartureRoute
  AppJobsRoute: typeof AppJobsRoute
  AppMedicalRoute: typeof AppMedicalRoute
  AppOfferRoute: typeof AppOfferRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSortedRoute: typeof AppSortedRoute
  AppTicketRoute: typeof AppTicketRoute
  AppVisaRoute: typeof AppVisaRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppliedRoute: AppAppliedRoute,
  AppBureauRoute: AppBureauRoute,
  AppCandidatesRoute: AppCandidatesRoute,
  AppDepartureRoute: AppDepartureRoute,
  AppJobsRoute: AppJobsRoute,
  AppMedicalRoute: AppMedicalRoute,
  AppOfferRoute: AppOfferRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSortedRoute: AppSortedRoute,
  AppTicketRoute: AppTicketRoute,
  AppVisaRoute: AppVisaRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  JobsRoute: JobsRoute,
  RecruitersRoute: RecruitersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
