/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as RecruitersRouteImport } from './routes/recruiters'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppCandidatesRouteImport } from './routes/app.candidates'
import { Route as AppCvListsRouteImport } from './routes/app.cv-lists'
import { Route as AppJobsRouteImport } from './routes/app.jobs'
import { Route as AppPipelineRouteImport } from './routes/app.pipeline'
import { Route as AppSettingsRouteImport } from './routes/app.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitersRoute = RecruitersRouteImport.update({
  id: '/recruiters',
  path: '/recruiters',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidatesRoute = AppCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AppRoute,
} as any)
const AppCvListsRoute = AppCvListsRouteImport.update({
  id: '/cv-lists',
  path: '/cv-lists',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/jobs': typeof JobsRoute
  '/recruiters': typeof RecruitersRoute
  '/app/candidates': typeof AppCandidatesRoute
  '/app/cv-lists': typeof AppCvListsRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/recruiters': typeof RecruitersRoute
  '/app/candidates': typeof AppCandidatesRoute
  '/app/cv-lists': typeof AppCvListsRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/jobs': typeof JobsRoute
  '/recruiters': typeof RecruitersRoute
  '/app/candidates': typeof AppCandidatesRoute
  '/app/cv-lists': typeof AppCvListsRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/jobs'
    | '/recruiters'
    | '/app/candidates'
    | '/app/cv-lists'
    | '/app/jobs'
    | '/app/pipeline'
    | '/app/settings'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/jobs'
    | '/recruiters'
    | '/app/candidates'
    | '/app/cv-lists'
    | '/app/jobs'
    | '/app/pipeline'
    | '/app/settings'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/jobs'
    | '/recruiters'
    | '/app/candidates'
    | '/app/cv-lists'
    | '/app/jobs'
    | '/app/pipeline'
    | '/app/settings'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  JobsRoute: typeof JobsRoute
  RecruitersRoute: typeof RecruitersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiters': {
      id: '/recruiters'
      path: '/recruiters'
      fullPath: '/recruiters'
      preLoaderRoute: typeof RecruitersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/candidates': {
      id: '/app/candidates'
      path: '/candidates'
      fullPath: '/app/candidates'
      preLoaderRoute: typeof AppCandidatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cv-lists': {
      id: '/app/cv-lists'
      path: '/cv-lists'
      fullPath: '/app/cv-lists'
      preLoaderRoute: typeof AppCvListsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/jobs': {
      id: '/app/jobs'
      path: '/jobs'
      fullPath: '/app/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pipeline': {
      id: '/app/pipeline'
      path: '/pipeline'
      fullPath: '/app/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCandidatesRoute: typeof AppCandidatesRoute
  AppCvListsRoute: typeof AppCvListsRoute
  AppJobsRoute: typeof AppJobsRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCandidatesRoute: AppCandidatesRoute,
  AppCvListsRoute: AppCvListsRoute,
  AppJobsRoute: AppJobsRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  JobsRoute: JobsRoute,
  RecruitersRoute: RecruitersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
